MvcPCRMatEng/Controllers/MasterController.cs
using MvcPCRMatEng.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic;
using System.Web;
using System.Web.Mvc;

namespace MvcPCRMatEng.Controllers
{
    public class MasterController : Controller
    {
        //
        // GET: /Master/

        PCRMatEngEntities dbPcr = new PCRMatEngEntities();
        TNC_ADMINEntities dbTNC = new TNC_ADMINEntities();

        //---------------------------------------------//
        [Check_Authen]
        public ActionResult Purpose()
        {
            ViewBag.Menu = 9;
            return View();
        }

        [HttpPost]
        public JsonResult PurposeList(int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            try
            {
                var query = dbPcr.TM_Purpose;

                //Get data from database
                int TotalRecord = query.Count();

                // Paging
                var output = query
                    .Select(s => new
                    {
                        s.purpose_id,
                        s.purpose_name,
                        s.del_flag
                        //del_flag = s.del_flag == true ? "Yes" : "No"
                    }).OrderBy(jtSorting).Skip(jtStartIndex).Take(jtPageSize);

                //Return result to jTable
                return Json(new { Result = "OK", Records = output, TotalRecordCount = TotalRecord });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult CreatePurpose()
        {
            try
            {
                var formData = byte.Parse(Request.Form["purpose_id"].ToString());
                var dbData = dbPcr.TM_Purpose.Where(w => w.purpose_id == formData).FirstOrDefault();
                if (dbData == null)
                {
                    TM_Purpose data = new TM_Purpose();
                    data.purpose_id = formData;
                    data.purpose_name = Request.Form["purpose_name"].ToString();
                    data.update_dt = DateTime.Now;
                    data.update_by = Session["PCRME_Auth"].ToString();

                    dbPcr.TM_Purpose.Add(data);
                }

                dbPcr.SaveChanges();

                return Json(new { Result = "OK", Record = dbPcr.TM_Purpose.OrderByDescending(o => o.update_dt).FirstOrDefault() });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult UpdatePurpose()
        {
            try
            {
                var id = byte.Parse(Request.Form["purpose_id"].ToString());
                var data = dbPcr.TM_Purpose.Find(id);
                data.purpose_name = Request.Form["purpose_name"].ToString();
                data.del_flag = Request.Form["del_flag"].ToString() == "0" ? false : true;
                data.update_dt = DateTime.Now;
                data.update_by = Session["PCRME_Auth"].ToString();
                dbPcr.SaveChanges();

                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult DeletePurpose()
        {
            try
            {
                var id = byte.Parse(Request.Form["purpose_id"].ToString());
                var data = dbPcr.TM_Purpose.Find(id);
                //data.del_flag = true;
                //data.update_dt = DateTime.Now;
                //data.update_by = Session["PCRME_Auth"].ToString();
                dbPcr.TM_Purpose.Remove(data);
                dbPcr.SaveChanges();

                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        //---------------------------------------------//
        [Check_Authen]
        public ActionResult Action()
        {
            ViewBag.Menu = 9;
            return View();
        }

        [HttpPost]
        public JsonResult ActionList(int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            try
            {
                var query = dbPcr.TM_Action;

                //Get data from database
                int TotalRecord = query.Count();

                // Paging
                var output = query
                    .Select(s => new
                    {
                        s.action_id,
                        s.action_name,
                        s.del_flag
                        //del_flag = s.del_flag == true ? "Yes" : "No"
                    }).OrderBy(jtSorting).Skip(jtStartIndex).Take(jtPageSize);

                //Return result to jTable
                return Json(new { Result = "OK", Records = output, TotalRecordCount = TotalRecord });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult CreateAction()
        {
            try
            {
                var formData = byte.Parse(Request.Form["action_id"].ToString());
                var dbData = dbPcr.TM_Action.Where(w => w.action_id == formData).FirstOrDefault();
                if (dbData == null)
                {
                    TM_Action data = new TM_Action();
                    data.action_id = formData;
                    data.action_name = Request.Form["action_name"].ToString();
                    data.update_dt = DateTime.Now;
                    data.update_by = Session["PCRME_Auth"].ToString();

                    dbPcr.TM_Action.Add(data);
                }

                dbPcr.SaveChanges();

                return Json(new { Result = "OK", Record = dbPcr.TM_Action.OrderByDescending(o => o.update_dt).FirstOrDefault() });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult UpdateAction()
        {
            try
            {
                var id = byte.Parse(Request.Form["action_id"].ToString());
                var data = dbPcr.TM_Action.Find(id);
                data.action_name = Request.Form["action_name"].ToString();
                data.del_flag = Request.Form["del_flag"].ToString() == "0" ? false : true;
                data.update_dt = DateTime.Now;
                data.update_by = Session["PCRME_Auth"].ToString();
                dbPcr.SaveChanges();

                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult DeleteAction()
        {
            try
            {
                var id = byte.Parse(Request.Form["action_id"].ToString());
                var data = dbPcr.TM_Action.Find(id);
                //data.del_flag = true;
                //data.update_dt = DateTime.Now;
                //data.update_by = Session["PCRME_Auth"].ToString();
                dbPcr.TM_Action.Remove(data);
                dbPcr.SaveChanges();

                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        //---------------------------------------------//
        [Check_Authen]
        public ActionResult Status()
        {
            ViewBag.Menu = 9;
            return View();
        }

        [HttpPost]
        public JsonResult StatusList(int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            try
            {
                var query = dbPcr.TM_Status;

                //Get data from database
                int TotalRecord = query.Count();

                // Paging
                var output = query
                    .Select(s => new
                    {
                        s.status_id,
                        s.status_name,
                        s.min_lv,
                        s.max_lv,
                        s.del_flag
                        //del_flag = s.del_flag == true ? "Yes" : "No"
                    }).OrderBy(jtSorting).Skip(jtStartIndex).Take(jtPageSize);

                //Return result to jTable
                return Json(new { Result = "OK", Records = output, TotalRecordCount = TotalRecord });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult CreateStatus()
        {
            try
            {
                var formData = byte.Parse(Request.Form["status_id"].ToString());
                var dbData = dbPcr.TM_Status.Where(w => w.status_id == formData).FirstOrDefault();
                if (dbData == null)
                {
                    TM_Status data = new TM_Status();
                    data.status_id = formData;
                    data.status_name = Request.Form["status_name"].ToString();
                    data.min_lv = byte.Parse(Request.Form["min_lv"].ToString());
                    data.max_lv = byte.Parse(Request.Form["max_lv"].ToString());
                    data.update_dt = DateTime.Now;
                    data.update_by = Session["PCRME_Auth"].ToString();

                    dbPcr.TM_Status.Add(data);
                }

                dbPcr.SaveChanges();

MvcPCRMatEng/Views/Master/Action.cshtml
@{
    ViewBag.Title = "Action";
}

<style type="text/css">
    /*fix jTable*/
    span.jtable-goto-page select, span.jtable-page-size-change select {
        height: 25px;
        width: 60px;
        padding: 2px 2px;
        margin-bottom:auto;
    }
    div.jtable-main-container table.jtable thead th {
        text-align: center;
    }
    div.jtable-main-container > table.jtable > tbody > tr.jtable-data-row > td {
        text-align: center;
    }
</style>
<script type="text/javascript">
    $(document).ready(function () {
        $('#jTableAction').jtable({
            title: 'Action Master',
            paging: true, //Enable paging
            pageSize: 10, //Set page size (default: 10)
            sorting: true, //Enable sorting
            selecting: true, //Enable selecting
            defaultSorting: 'action_id', //Set default sorting
            actions: {
                listAction: '@Url.Action("ActionList","Master")',
                @*deleteAction: '@Url.Action("DeleteAction","Master")',*@
                updateAction: '@Url.Action("UpdateAction","Master")',
                createAction: '@Url.Action("CreateAction","Master")'
            },
            fields: {
                action_id: { title: 'ID', key: true, create: true, edit: false, width: '10%' },
                action_name: { title: 'Action Name', create: true, edit: true, width: '75%' },
                del_flag: { title: 'Status', create: false, edit: true, width: '15%', options: { 0: 'Active', 1: 'Inactive' } }
            }
        });
        //Load student list from server
        $('#jTableAction').jtable('load');

    });
</script>

<div id="jTableAction"></div>

MvcPCRMatEng/Views/Master/GroupCode.cshtml
@{
    ViewBag.Title = "Group Code";
}

<style type="text/css">
    /*fix jTable*/
    span.jtable-goto-page select, span.jtable-page-size-change select {
        height: 25px;
        width: 60px;
        padding: 2px 2px;
        margin-bottom:auto;
    }
    div.jtable-main-container table.jtable thead th {
        text-align: center;
    }
    div.jtable-main-container > table.jtable > tbody > tr.jtable-data-row > td {
        text-align: center;
    }
</style>
<script type="text/javascript">
    $(document).ready(function () {
        $('#jTableGCode').jtable({
            title: 'Group Code Master',
            paging: true, //Enable paging
            pageSize: 10, //Set page size (default: 10)
            sorting: true, //Enable sorting
            selecting: true, //Enable selecting
            defaultSorting: 'group_id', //Set default sorting
            actions: {
                listAction: '@Url.Action("GCodeList","Master")',
                @*deleteAction: '@Url.Action("DeleteGCode","Master")',*@
                updateAction: '@Url.Action("UpdateGCode","Master")',
                createAction: '@Url.Action("CreateGCode","Master")'
            },
            fields: {
                group_id: { title: 'Group', key: true, create: true, edit: false, width: '55%', options: '@Url.Action("GetTNCGroupList","Master")' },
                group_code: { title: 'Code', create: true, edit: true, width: '30%' },
                del_flag: { title: 'Status', create: false, edit: true, width: '15%', options: { 0: 'Active', 1: 'Inactive' } }
            }
        });
        //Load student list from server
        $('#jTableGCode').jtable('load');

    });
</script>

<div id="jTableGCode"></div>

MvcPCRMatEng/Views/Master/Level.cshtml
@{
    ViewBag.Title = "Level";
}

<style type="text/css">
    /*fix jTable*/
    span.jtable-goto-page select, span.jtable-page-size-change select {
        height: 25px;
        width: 60px;
        padding: 2px 2px;
        margin-bottom:auto;
    }
    div.jtable-main-container table.jtable thead th {
        text-align: center;
    }
    div.jtable-main-container > table.jtable > tbody > tr.jtable-data-row > td {
        text-align: center;
    }
</style>
<script type="text/javascript">
    $(document).ready(function () {
        $('#jTableLevel').jtable({
            title: 'Level Master',
            paging: true, //Enable paging
            pageSize: 10, //Set page size (default: 10)
            sorting: true, //Enable sorting
            selecting: true, //Enable selecting
            defaultSorting: 'lv_id', //Set default sorting
            actions: {
                listAction: '@Url.Action("LevelList","Master")',
                @*deleteAction: '@Url.Action("DeleteLevel","Master")',*@
                updateAction: '@Url.Action("UpdateLevel","Master")',
                createAction: '@Url.Action("CreateLevel","Master")'
            },
            fields: {
                lv_id: { title: 'ID', key: true, create: true, edit: false, width: '10%' },
                lv_name: { title: 'Level Name', create: true, edit: true, width: '45%' },
                pos_min: { title: 'Position Min', create: true, edit: true, width: '15%' },
                pos_max: { title: 'Position Max', create: true, edit: true, width: '15%' },
                del_flag: { title: 'Status', create: false, edit: true, width: '15%', options: { 0: 'Active', 1: 'Inactive' } }
            }
        });
        //Load student list from server
        $('#jTableLevel').jtable('load');

    });
</script>

<div id="jTableLevel"></div>

MvcPCRMatEng/Views/Master/Purpose.cshtml
@{
    ViewBag.Title = "Purpose";
}

<style type="text/css">
    /*fix jTable*/
    span.jtable-goto-page select, span.jtable-page-size-change select {
        height: 25px;
        width: 60px;
        padding: 2px 2px;
        margin-bottom:auto;
    }
    div.jtable-main-container table.jtable thead th {
        text-align: center;
    }
    div.jtable-main-container > table.jtable > tbody > tr.jtable-data-row > td {
        text-align: center;
    }
</style>
<script type="text/javascript">
    $(document).ready(function () {
        $('#jTablePurpose').jtable({
            title: 'Purpose Master',
            paging: true, //Enable paging
            pageSize: 10, //Set page size (default: 10)
            sorting: true, //Enable sorting
            selecting: true, //Enable selecting
            defaultSorting: 'purpose_id', //Set default sorting
            actions: {
                listAction: '@Url.Action("PurposeList","Master")',
                @*deleteAction: '@Url.Action("DeletePurpose","Master")',*@
                updateAction: '@Url.Action("UpdatePurpose","Master")',
                createAction: '@Url.Action("CreatePurpose","Master")'
            },
            fields: {
                purpose_id: { title: 'ID', key: true, create: false, edit: false, width: '10%' },
                purpose_name: { title: 'Purpose Name', create: true, edit: true, width: '75%' },
                del_flag: { title: 'Status', create: false, edit: true, width: '15%', options: { 0: 'Active', 1: 'Inactive' } }
            }
        });
        //Load student list from server
        $('#jTablePurpose').jtable('load');

    });
</script>

<div id="jTablePurpose"></div>

MvcPCRMatEng/Views/Master/Status.cshtml
@{
    ViewBag.Title = "Status";
}

<style type="text/css">
    /*fix jTable*/
    span.jtable-goto-page select, span.jtable-page-size-change select {
        height: 25px;
        width: 60px;
        padding: 2px 2px;
        margin-bottom:auto;
    }
    div.jtable-main-container table.jtable thead th {
        text-align: center;
    }
    div.jtable-main-container > table.jtable > tbody > tr.jtable-data-row > td {
        text-align: center;
    }
</style>
<script type="text/javascript">
    $(document).ready(function () {
        $('#jTableStatus').jtable({
            title: 'Status Master',
            paging: true, //Enable paging
            pageSize: 10, //Set page size (default: 10)
            sorting: true, //Enable sorting
            selecting: true, //Enable selecting
            defaultSorting: 'status_id', //Set default sorting
            actions: {
                listAction: '@Url.Action("StatusList","Master")',
                @*deleteAction: '@Url.Action("DeleteStatus","Master")',*@
                updateAction: '@Url.Action("UpdateStatus","Master")',
                createAction: '@Url.Action("CreateStatus","Master")'
            },
            fields: {
                status_id: { title: 'ID', key: true, create: true, edit: false, width: '10%' },
                status_name: { title: 'Status Name', create: true, edit: true, width: '45%' },
                min_lv: { title: 'Level Min', create: true, edit: true, width: '15%', options: '@Url.Action("GetLevelList","Master")' },
                max_lv: { title: 'Level Max', create: true, edit: true, width: '15%', options: '@Url.Action("GetLevelList","Master")' },
                del_flag: { title: 'Status', create: false, edit: true, width: '15%', options: { 0: 'Active', 1: 'Inactive' } }
            }
        });
        //Load student list from server
        $('#jTableStatus').jtable('load');

    });
</script>

<div id="jTableStatus"></div>

MvcPCRMatEng/Views/Master/Supervisor.cshtml
@{
    ViewBag.Title = "Supervisor";
}

<style type="text/css">
    /*fix jTable*/
    span.jtable-goto-page select, span.jtable-page-size-change select {
        height: 25px;
        width: 60px;
        padding: 2px 2px;
        margin-bottom:auto;
    }
    div.jtable-main-container table.jtable thead th {
        text-align: center;
    }
    div.jtable-main-container > table.jtable > tbody > tr.jtable-data-row > td {
        text-align: center;
    }
</style>
<script type="text/javascript">
    $(document).ready(function () {
        $('#jTableSup').jtable({
            title: 'Supervisor Master',
            paging: true, //Enable paging
            pageSize: 10, //Set page size (default: 10)
            sorting: true, //Enable sorting
            selecting: true, //Enable selecting
            defaultSorting: 'group_id', //Set default sorting
            actions: {
                listAction: '@Url.Action("SupList","Master")',
                @*deleteAction: '@Url.Action("DeleteSup","Master")',*@
                updateAction: '@Url.Action("UpdateSup","Master")',
                createAction: '@Url.Action("CreateSup","Master")'
            },
            fields: {
                emp_code: { title: 'User', key: true, create: true, edit: false, width: '50%', options: '@Url.Action("GetTNCUserList","Master")' },
                group_id: { title: 'Group', key: true, create: true, edit: false, width: '25%', options: '@Url.Action("GetInternalGroupList","Master")' },
                email_flag: { title: 'Receive Email', create: true, edit: true, width: '15%', options: { 0: 'No', 1: 'Yes' } },
                update_dt: { title: 'Update Date', create: false, edit: false, width: '20%', type: 'date', displayFormat: 'dd-mm-yy' },
                btnDelete: {
                    title: '',
                    width: '2%', create: false, edit: false, sorting: false,
                    display: function (data) {
                        return $('<button type="button" class="btn btn-mini UDel" data-emp="' + data.record.emp_code + '" data-group="' + data.record.group_id + '"><i class="icon-trash"></i></a>');
                    }
                }
            }
        });
        //Load student list from server
        $('#jTableSup').jtable('load');

        $(document).on("click", ".UDel", function (event) {
            var obj = new Object();
            obj.emp_code = $(this).attr("data-emp");
            obj.group_id = $(this).attr("data-group");
            if (confirm("Are you sure to Delete ?")) {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("DeleteSup","Master")",
                    data: obj,
                    dataType: "json",
                    success: function (data) {
                        $('#jTableSup').jtable('reload');
                    },
                    error: function (request, status, err) {
                        alert("Request:" + request + ", Status:" + status + ", Error:" + err);
                    }
                });
            }
            return false;
        });
    });
</script>

<div id="jTableSup"></div>

MvcPCRMatEng/Views/Master/UserType.cshtml
@{
    ViewBag.Title = "User Type";
}

<style type="text/css">
    /*fix jTable*/
    span.jtable-goto-page select, span.jtable-page-size-change select {
        height: 25px;
        width: 60px;
        padding: 2px 2px;
        margin-bottom:auto;
    }
    div.jtable-main-container table.jtable thead th {
        text-align: center;
    }
    div.jtable-main-container > table.jtable > tbody > tr.jtable-data-row > td {
        text-align: center;
    }
</style>
<script type="text/javascript">
    $(document).ready(function () {
        $('#jTableUType').jtable({
            title: 'User Type Master',
            paging: true, //Enable paging
            pageSize: 10, //Set page size (default: 10)
            sorting: true, //Enable sorting
            selecting: true, //Enable selecting
            defaultSorting: 'utype_id', //Set default sorting
            actions: {
                listAction: '@Url.Action("UserTypeList","Master")',
                deleteAction: '@Url.Action("DeleteUserType","Master")',
                updateAction: '@Url.Action("UpdateUserType","Master")',
                createAction: '@Url.Action("CreateUserType","Master")'
            },
            fields: {
                utype_id: { title: 'ID', key: true, create: true, edit: false, width: '10%' },
                utype_name: { title: 'User Type', create: true, edit: true, width: '75%' },
                del_flag: { title: 'Deleted', create: false, edit: false, width: '15%' }
            }
        });
        //Load student list from server
        $('#jTableUType').jtable('load');

    });
</script>

<div id="jTableUType"></div>

MvcPCRMatEng/Views/Master/Users.cshtml
@{
    ViewBag.Title = "User";
}

<style type="text/css">
    /*fix jTable*/
    span.jtable-goto-page select, span.jtable-page-size-change select {
        height: 25px;
        width: 60px;
        padding: 2px 2px;
        margin-bottom:auto;
    }
    div.jtable-main-container table.jtable thead th {
        text-align: center;
    }
    div.jtable-main-container > table.jtable > tbody > tr.jtable-data-row > td {
        text-align: center;
    }
</style>
<script type="text/javascript">
    $(document).ready(function () {
        $('#jTableUser').jtable({
            title: 'User Master',
            paging: true, //Enable paging
            pageSize: 10, //Set page size (default: 10)
            sorting: true, //Enable sorting
            selecting: true, //Enable selecting
            defaultSorting: 'utype_id', //Set default sorting
            actions: {
                listAction: '@Url.Action("UserList","Master")',
                @*deleteAction: '@Url.Action("DeleteUser","Master")',
                updateAction: '@Url.Action("UpdateUser","Master")',*@
                createAction: '@Url.Action("CreateUser","Master")'
            },
            fields: {
                emp_code: { title: 'Name', key: true, create: true, edit: false, width: '50%', options: '@Url.Action("GetTNCUserList","Master")' },
                utype_id: { title: 'User Type', key: true, create: true, edit: false, width: '25%', options: '@Url.Action("GetUTypeList","Master")' },
                update_dt: { title: 'Update Date', create: false, edit: false, width: '20%', type: 'date', displayFormat: 'dd-mm-yy' },
                btnDelete: {
                    title: '',
                    width: '2%', create: false, edit: false, sorting: false,
                    display: function (data) {
                        return $('<button type="button" class="btn btn-mini UDel" data-emp="' + data.record.emp_code + '" data-utype="' + data.record.utype_id + '"><i class="icon-trash"></i></a>');
                    }
                }
            }
        });
        //Load student list from server
        $('#jTableUser').jtable('load');

        $(document).on("click", ".UDel", function (event) {
            var obj = new Object();
            obj.emp_code = $(this).attr("data-emp");
            obj.utype_id = $(this).attr("data-utype");
            if (confirm("Are you sure to Delete ?")) {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("DeleteUser","Master")",
                    data: obj,
                    dataType: "json",
                    success: function (data) {
                        $('#jTableUser').jtable('reload');
                    },
                    error: function (request, status, err) {
                        alert("Request:" + request + ", Status:" + status + ", Error:" + err);
                    }
                });
            }
            return false;
        });
    });
</script>

<div id="jTableUser"></div>